### ISSUE TITLE
[Feature Request] Change Notification message to a template selector

### ISSUE THREAD

**Issue by TFWol** [Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices#10]
I think it may be a good idea to change notify_message to a template selector like you have with notify_title.

This:
```yaml
  notify_message:
    name: Notification message
    description: Notification message
    required: true
    example: There is somebody at the door!
    selector:
      select:
        options:
          - TTS
          - remove_channel
          - clear_notification
          - There is somebody at the door!
          - There is somebody in the garden!
        custom_value: true
        multiple: false
```
to this:

```yaml
  notify_message:
    name: Notification message
    description: Notification message
    required: true
    example: There is somebody at the door!
    selector:
      template:
```

It would allow typing something like `Computer is: {{states('binary_sensor.pc_powerstate')}}` without being forced into YAML only mode (something I wish home assistant didn't do).

To see what I mean just paste in some Jinja code into the Notification message field and click out of it. You won't be able to use the UI anymore.

IMO, a major feature of your script is the UI so the benefit would outweigh the cons.

Then again, you might have a reason since it currently demonstrates things like `clear_notification` without needing to look at the documentation.
